/**
 * Tests for Login Form Validation (script.js)
 * Generated by: test-gen-core (Post-Impl Mode)
 * 
 * Run: Open script.test.html in a browser to see results.
 * (Minimal test runner — no Node.js dependency needed for this demo)
 */

// ============================================================
// Minimal Test Runner (inline, since this is a browser-only demo)
// ============================================================

const testResults = { passed: 0, failed: 0, tests: [] };

/**
 * Runs a single test case.
 * @param {string} name - Descriptive test name.
 * @param {function} fn - Test function containing assertions.
 */
function test(name, fn) {
    try {
        fn();
        testResults.passed++;
        testResults.tests.push({ name, status: 'PASS' });
    } catch (err) {
        testResults.failed++;
        testResults.tests.push({ name, status: 'FAIL', error: err.message });
    }
}

/**
 * Asserts that a value is strictly equal to the expected value.
 * @param {*} actual - The actual value.
 * @param {*} expected - The expected value.
 * @param {string} [label] - Optional description for the assertion.
 */
function assertEqual(actual, expected, label) {
    if (actual !== expected) {
        throw new Error(
            (label ? label + ': ' : '') +
            'Expected ' + JSON.stringify(expected) + ' but got ' + JSON.stringify(actual)
        );
    }
}

/**
 * Asserts that a value is truthy.
 * @param {*} value - The value to check.
 * @param {string} [label] - Optional description.
 */
function assertTrue(value, label) {
    if (!value) {
        throw new Error((label ? label + ': ' : '') + 'Expected truthy but got ' + JSON.stringify(value));
    }
}

/**
 * Asserts that a value is falsy.
 * @param {*} value - The value to check.
 * @param {string} [label] - Optional description.
 */
function assertFalse(value, label) {
    if (value) {
        throw new Error((label ? label + ': ' : '') + 'Expected falsy but got ' + JSON.stringify(value));
    }
}

/** Prints test results to console and to the page. */
function reportResults() {
    console.log('\n========== TEST RESULTS ==========');
    testResults.tests.forEach(function (t) {
        const icon = t.status === 'PASS' ? '✅' : '❌';
        console.log(icon + ' ' + t.name);
        if (t.error) {
            console.log('   → ' + t.error);
        }
    });
    console.log('==================================');
    console.log('Passed: ' + testResults.passed + ' | Failed: ' + testResults.failed);

    // Render to page if container exists
    const container = document.getElementById('test-output');
    if (container) {
        let html = '<h2>Test Results: ' + testResults.passed + ' passed, ' + testResults.failed + ' failed</h2>';
        testResults.tests.forEach(function (t) {
            const cls = t.status === 'PASS' ? 'pass' : 'fail';
            html += '<div class="test-' + cls + '">';
            html += (t.status === 'PASS' ? '✅' : '❌') + ' ' + t.name;
            if (t.error) {
                html += '<br><small>' + t.error + '</small>';
            }
            html += '</div>';
        });
        container.innerHTML = html;
    }
}

// ============================================================
// Tests: validateEmail
// ============================================================

// --- Happy Path ---
test('validateEmail_validStandardEmail_returnsValid', function () {
    // Arrange
    const email = 'user@example.com';
    // Act
    const result = validateEmail(email);
    // Assert
    assertTrue(result.valid, 'should be valid');
    assertEqual(result.message, '', 'message should be empty');
});

test('validateEmail_validEmailWithSubdomain_returnsValid', function () {
    const result = validateEmail('admin@mail.company.co');
    assertTrue(result.valid);
});

test('validateEmail_validEmailWithPlus_returnsValid', function () {
    const result = validateEmail('user+tag@example.com');
    assertTrue(result.valid);
});

// --- Edge Cases ---
test('validateEmail_emptyString_returnsInvalid', function () {
    const result = validateEmail('');
    assertFalse(result.valid);
    assertEqual(result.message, 'Email is required.');
});

test('validateEmail_null_returnsInvalid', function () {
    const result = validateEmail(null);
    assertFalse(result.valid);
    assertEqual(result.message, 'Email is required.');
});

test('validateEmail_undefined_returnsInvalid', function () {
    const result = validateEmail(undefined);
    assertFalse(result.valid);
    assertEqual(result.message, 'Email is required.');
});

test('validateEmail_whitespaceOnly_returnsInvalid', function () {
    const result = validateEmail('   ');
    assertFalse(result.valid);
    assertEqual(result.message, 'Email is required.');
});

// --- Error Cases ---
test('validateEmail_noAtSign_returnsInvalid', function () {
    const result = validateEmail('userexample.com');
    assertFalse(result.valid);
    assertEqual(result.message, 'Please enter a valid email address.');
});

test('validateEmail_noDomain_returnsInvalid', function () {
    const result = validateEmail('user@');
    assertFalse(result.valid);
});

test('validateEmail_noTLD_returnsInvalid', function () {
    const result = validateEmail('user@example');
    assertFalse(result.valid);
});

test('validateEmail_doubleAt_returnsInvalid', function () {
    const result = validateEmail('user@@example.com');
    assertFalse(result.valid);
});

// ============================================================
// Tests: validatePassword
// ============================================================

// --- Happy Path ---
test('validatePassword_validEightChars_returnsValid', function () {
    const result = validatePassword('abcd1234');
    assertTrue(result.valid);
    assertEqual(result.message, '');
});

test('validatePassword_validLongPassword_returnsValid', function () {
    const result = validatePassword('thisIsAVeryLongAndSecurePassword!123');
    assertTrue(result.valid);
});

// --- Edge Cases ---
test('validatePassword_exactlyEightChars_returnsValid', function () {
    const result = validatePassword('12345678');
    assertTrue(result.valid, 'boundary: exactly 8 chars should pass');
});

test('validatePassword_sevenChars_returnsInvalid', function () {
    const result = validatePassword('1234567');
    assertFalse(result.valid, 'boundary: 7 chars should fail');
    assertEqual(result.message, 'Password must be at least 8 characters.');
});

test('validatePassword_emptyString_returnsInvalid', function () {
    const result = validatePassword('');
    assertFalse(result.valid);
    assertEqual(result.message, 'Password is required.');
});

test('validatePassword_null_returnsInvalid', function () {
    const result = validatePassword(null);
    assertFalse(result.valid);
    assertEqual(result.message, 'Password is required.');
});

test('validatePassword_undefined_returnsInvalid', function () {
    const result = validatePassword(undefined);
    assertFalse(result.valid);
    assertEqual(result.message, 'Password is required.');
});

// --- Special Characters ---
test('validatePassword_specialCharsOnly_validIfLongEnough', function () {
    const result = validatePassword('!@#$%^&*');
    assertTrue(result.valid, 'special chars should be allowed');
});

test('validatePassword_spacesAllowed_validIfLongEnough', function () {
    const result = validatePassword('pass word 1');
    assertTrue(result.valid, 'spaces should be allowed in passwords');
});

// ============================================================
// Run & Report
// ============================================================
reportResults();
